// localStorageSetup.js
const dummyData = [
  {
    id: 1,
    photo: "https://randomuser.me/api/portraits/men/1.jpg",
    name: "John Doe",
    rfidId: "1234567890",
    position: "Manager",
    address: "Jl. Merdeka No. 1, Jakarta",
    gender: "Laki-laki",
  },
  {
    id: 2,
    photo: "https://randomuser.me/api/portraits/women/1.jpg",
    name: "Jane Smith",
    rfidId: "0987654321",
    position: "Staff",
    address: "Jl. Kebon Jeruk No. 2, Tangerang",
    gender: "Perempuan",
  },
  {
    id: 3,
    photo: "https://randomuser.me/api/portraits/men/2.jpg",
    name: "Robert Brown",
    rfidId: "1122334455",
    position: "Supervisor",
    address: "Jl. Raya No. 3, Bandung",
    gender: "Laki-laki",
  },
  {
    id: 4,
    photo: "https://randomuser.me/api/portraits/women/2.jpg",
    name: "Emily Davis",
    rfidId: "2233445566",
    position: "Secretary",
    address: "Jl. Indah No. 4, Jakarta",
    gender: "Perempuan",
  },
  {
    id: 5,
    photo: "https://randomuser.me/api/portraits/men/3.jpg",
    name: "Michael Johnson",
    rfidId: "3344556677",
    position: "Developer",
    address: "Jl. Sejahtera No. 5, Surabaya",
    gender: "Laki-laki",
  },
  {
    id: 6,
    photo: "https://randomuser.me/api/portraits/women/3.jpg",
    name: "Sophia Lee",
    rfidId: "4455667788",
    position: "Designer",
    address: "Jl. Pemuda No. 6, Medan",
    gender: "Perempuan",
  },
  {
    id: 7,
    photo: "https://randomuser.me/api/portraits/men/4.jpg",
    name: "David Wilson",
    rfidId: "5566778899",
    position: "Team Lead",
    address: "Jl. Pahlawan No. 7, Makassar",
    gender: "Laki-laki",
  },
  {
    id: 8,
    photo: "https://randomuser.me/api/portraits/women/4.jpg",
    name: "Olivia Miller",
    rfidId: "6677889900",
    position: "HR Manager",
    address: "Jl. Cendana No. 8, Bali",
    gender: "Perempuan",
  },
  {
    id: 9,
    photo: "https://randomuser.me/api/portraits/men/5.jpg",
    name: "Daniel Moore",
    rfidId: "7788990011",
    position: "Admin",
    address: "Jl. Angkasa No. 9, Yogyakarta",
    gender: "Laki-laki",
  },
  {
    id: 10,
    photo: "https://randomuser.me/api/portraits/women/5.jpg",
    name: "Isabella Taylor",
    rfidId: "8899001122",
    position: "Marketing",
    address: "Jl. Srikandi No. 10, Solo",
    gender: "Perempuan",
  },
  {
    id: 11,
    photo: "https://randomuser.me/api/portraits/men/6.jpg",
    name: "Matthew Martinez",
    rfidId: "9900112233",
    position: "Sales Manager",
    address: "Jl. Merpati No. 11, Palembang",
    gender: "Laki-laki",
  },
  {
    id: 12,
    photo: "https://randomuser.me/api/portraits/women/6.jpg",
    name: "Ava Anderson",
    rfidId: "1002233445",
    position: "Accountant",
    address: "Jl. Cemara No. 12, Semarang",
    gender: "Perempuan",
  },
  {
    id: 13,
    photo: "https://randomuser.me/api/portraits/men/7.jpg",
    name: "James Jackson",
    rfidId: "2113344556",
    position: "Consultant",
    address: "Jl. Raya No. 13, Depok",
    gender: "Laki-laki",
  },
  {
    id: 14,
    photo: "https://randomuser.me/api/portraits/women/7.jpg",
    name: "Charlotte White",
    rfidId: "3224455667",
    position: "IT Specialist",
    address: "Jl. Maju No. 14, Surakarta",
    gender: "Perempuan",
  },
  {
    id: 15,
    photo: "https://randomuser.me/api/portraits/men/8.jpg",
    name: "William Harris",
    rfidId: "4335566778",
    position: "Engineer",
    address: "Jl. Cikarang No. 15, Lampung",
    gender: "Laki-laki",
  },
  {
    id: 16,
    photo: "https://randomuser.me/api/portraits/women/8.jpg",
    name: "Mia Clark",
    rfidId: "5446677889",
    position: "Customer Support",
    address: "Jl. Satria No. 16, Cirebon",
    gender: "Perempuan",
  },
  {
    id: 17,
    photo: "https://randomuser.me/api/portraits/men/9.jpg",
    name: "Ethan Lewis",
    rfidId: "6557788990",
    position: "Security",
    address: "Jl. Merdeka No. 17, Surabaya",
    gender: "Laki-laki",
  },
  {
    id: 18,
    photo: "https://randomuser.me/api/portraits/women/9.jpg",
    name: "Amelia Robinson",
    rfidId: "7668899001",
    position: "Chef",
    address: "Jl. Puncak No. 18, Jakarta",
    gender: "Perempuan",
  },
  {
    id: 19,
    photo: "https://randomuser.me/api/portraits/men/10.jpg",
    name: "Benjamin Walker",
    rfidId: "8779900112",
    position: "Technician",
    address: "Jl. Bunga No. 19, Medan",
    gender: "Laki-laki",
  },
  {
    id: 20,
    photo: "https://randomuser.me/api/portraits/women/10.jpg",
    name: "Harper Hall",
    rfidId: "9881011223",
    position: "Assistant",
    address: "Jl. Melati No. 20, Malang",
    gender: "Perempuan",
  },
];

// Cek jika data karyawan belum ada di localStorage
if (!localStorage.getItem("karyawanData")) {
  // Jika belum ada, simpan data dummy ke localStorage
  localStorage.setItem("karyawanData", JSON.stringify(dummyData));
}
